// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"database/sql"
	"time"
)

type Category struct {
	ID int64 `json:"id"`
	// 分类名称
	Name string `json:"name"`
	// 修改时间
	UpdatedAt time.Time `json:"updated_at"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
}

type Collection struct {
	ID int64 `json:"id"`
	// 收藏者的用户ID
	UserID int32 `json:"user_id"`
	// 收藏的新闻ID
	NewsID int32 `json:"news_id"`
	// 修改时间
	UpdatedAt time.Time `json:"updated_at"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
}

type Comment struct {
	ID int64 `json:"id"`
	// 评论内容
	Content string `json:"content"`
	// 点赞人数
	Likes sql.NullInt32 `json:"likes"`
	// 父评论ID
	ParentID int32 `json:"parent_id"`
	// 评论人ID
	UserID int32 `json:"user_id"`
	// 评论新闻ID
	NewsID int32 `json:"news_id"`
	// 修改时间
	UpdatedAt time.Time `json:"updated_at"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
}

type CommentLike struct {
	ID int64 `json:"id"`
	// 点赞评论ID
	CommentID int32 `json:"comment_id"`
	// 点赞用户ID
	UserID int32 `json:"user_id"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 修改时间
	UpdatedAt time.Time `json:"updated_at"`
}

type News struct {
	ID int64 `json:"id"`
	// 新闻标题
	Title string `json:"title"`
	// 新闻来源
	Source string `json:"source"`
	// 新闻摘要
	Digital string `json:"digital"`
	// 新闻内容
	Content string `json:"content"`
	// 新闻浏览量
	Clicks sql.NullInt32 `json:"clicks"`
	// 0-通过,1-审核中,2-不通过
	Status int32 `json:"status"`
	// 不通过的理由
	Reason sql.NullString `json:"reason"`
	// 新闻图片,序列化后的串
	Images sql.NullString `json:"images"`
	// 修改时间
	UpdatedAt time.Time `json:"updated_at"`
	// 创建时间
	CreatedAt  time.Time `json:"created_at"`
	CategoryID int32     `json:"category_id"`
	UserID     int32     `json:"user_id"`
}

type User struct {
	ID int64 `json:"id"`
	// 昵称
	Nickname string `json:"nickname"`
	// 用户名
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
	// 手机号
	Phone string `json:"phone"`
	// 邮箱
	Email string `json:"email"`
	// 头像地址
	Avatar string `json:"avatar"`
	// 最后一次登陆时间
	LastLoginAt time.Time `json:"last_login_at"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 修改时间
	UpdatedAt time.Time `json:"updated_at"`
}

type UserFan struct {
	ID int64 `json:"id"`
	// 关注者ID
	FollowerID int32 `json:"follower_id"`
	// 被关注者ID
	FollowedID int32 `json:"followed_id"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 修改时间
	UpdatedAt time.Time `json:"updated_at"`
}
